"""LocalStorage and the upload/serving endpoints (PLAN.md Phase 6)."""
from datetime import timedelta

import pytest
from sqlmodel import select

from app.auth.models import Role, User
from app.auth.security import hash_password
from app.events.models import Event
from app.storage.service import LocalStorage, StorageError
from app.submissions.models import Submission, SubmissionStatus
from app.teams.models import Team, TeamMembership
from app.timeutil import utcnow

# A tiny valid 1x1 PNG, so real image bytes flow through save()/read() rather
# than an arbitrary blob that happens to pass content-type checks alone.
PNG_1PX = bytes.fromhex(
    "89504e470d0a1a0a0000000d494844440000000100000001080600000"
    "01f15c4890000000a49444154789c6360000002000155e28f760000000049454e44ae426082"
)


def _user(session, email: str, role: Role = Role.participant) -> User:
    user = User(email=email, name=email.split("@")[0], role=role, password_hash=hash_password("supersecret1"))
    session.add(user)
    session.commit()
    session.refresh(user)
    return user


def _login_as(client, session, email: str) -> None:
    client.post("/api/auth/logout")
    client.post("/api/auth/login", json={"email": email, "password": "supersecret1"})


def _event(session, slug: str) -> Event:
    owner = _user(session, f"{slug}-owner@example.com", Role.organizer)
    event = Event(
        slug=slug, name="Storage Event",
        start_at=utcnow() - timedelta(days=1), end_at=utcnow() + timedelta(days=1),
        created_by_id=owner.id,
    )
    session.add(event)
    session.commit()
    session.refresh(event)
    return event


def _team_with_submission(session, event: Event, member_email: str, name: str) -> tuple[Team, Submission]:
    member = _user(session, member_email)
    team = Team(event_id=event.id, name=name)
    session.add(team)
    session.commit()
    session.refresh(team)
    session.add(TeamMembership(team_id=team.id, user_id=member.id))
    submission = Submission(team_id=team.id, event_id=event.id, title="Widget", description="d",
                             status=SubmissionStatus.submitted)
    session.add(submission)
    session.commit()
    session.refresh(submission)
    return team, submission


# ---------------------------------------------------------------------------
# LocalStorage (pure, no DB)
# ---------------------------------------------------------------------------

def test_local_storage_saves_and_reads_back_bytes(tmp_path):
    storage = LocalStorage(tmp_path)
    key = storage.save(PNG_1PX, "image/png")
    assert storage.exists(key)
    assert storage.read(key) == PNG_1PX


def test_local_storage_rejects_an_unsupported_content_type(tmp_path):
    storage = LocalStorage(tmp_path)
    with pytest.raises(StorageError, match="Unsupported image type"):
        storage.save(PNG_1PX, "application/pdf")


def test_local_storage_rejects_an_oversized_file(tmp_path):
    storage = LocalStorage(tmp_path)
    too_big = b"\x00" * (5 * 1024 * 1024 + 1)
    with pytest.raises(StorageError, match="must be under"):
        storage.save(too_big, "image/png")


def test_local_storage_cannot_be_made_to_write_outside_its_root(tmp_path):
    """A key is always generated by save() itself, never accepted from a
    caller -- this proves _resolve() would refuse one even if some future bug
    ever let a crafted key reach it."""
    storage = LocalStorage(tmp_path)
    with pytest.raises(StorageError, match="Invalid file key"):
        storage._resolve("../../etc/passwd")
    with pytest.raises(StorageError, match="Invalid file key"):
        storage._resolve("../outside.png")


# ---------------------------------------------------------------------------
# Upload endpoints
# ---------------------------------------------------------------------------

def test_a_team_member_can_upload_their_submissions_image(client, session):
    event = _event(session, "storage-upload")
    team, submission = _team_with_submission(session, event, "upload-member@example.com", "Team Upload")
    _login_as(client, session, "upload-member@example.com")

    r = client.post(
        f"/api/teams/{team.id}/submission/image",
        files={"file": ("shot.png", PNG_1PX, "image/png")},
    )
    assert r.status_code == 200, r.text
    image_url = r.json()["image_url"]
    assert image_url.startswith("/media/")

    served = client.get(image_url)
    assert served.status_code == 200
    assert served.headers["content-type"] == "image/png"
    assert served.content == PNG_1PX


def test_uploading_again_replaces_the_old_image_rather_than_orphaning_it(client, session):
    event = _event(session, "storage-replace")
    team, _submission = _team_with_submission(session, event, "replace-member@example.com", "Team Replace")
    _login_as(client, session, "replace-member@example.com")

    first = client.post(
        f"/api/teams/{team.id}/submission/image", files={"file": ("a.png", PNG_1PX, "image/png")}
    ).json()["image_url"]
    second = client.post(
        f"/api/teams/{team.id}/submission/image", files={"file": ("b.png", PNG_1PX, "image/png")}
    ).json()["image_url"]

    assert first != second
    # The old key is gone, not merely unreferenced -- it 404s, it doesn't still serve.
    assert client.get(first).status_code == 404
    assert client.get(second).status_code == 200


def test_a_non_member_cannot_upload_to_someone_elses_submission(client, session):
    event = _event(session, "storage-cross-team")
    team, _submission = _team_with_submission(session, event, "owner-member@example.com", "Team Owner")
    _user(session, "outsider@example.com")
    _login_as(client, session, "outsider@example.com")

    r = client.post(
        f"/api/teams/{team.id}/submission/image", files={"file": ("shot.png", PNG_1PX, "image/png")}
    )
    assert r.status_code == 403


def test_upload_rejects_a_disallowed_content_type_with_a_plain_message(client, session):
    event = _event(session, "storage-bad-type")
    team, _submission = _team_with_submission(session, event, "badtype-member@example.com", "Team Bad Type")
    _login_as(client, session, "badtype-member@example.com")

    r = client.post(
        f"/api/teams/{team.id}/submission/image",
        files={"file": ("doc.pdf", b"%PDF-1.4", "application/pdf")},
    )
    assert r.status_code == 422
    assert "Unsupported image type" in r.json()["detail"]


def test_avatar_upload_is_self_only_and_shows_up_on_me(client, session):
    _user(session, "avatar-user@example.com")
    _login_as(client, session, "avatar-user@example.com")

    before = client.get("/api/auth/me").json()
    assert before["avatar_url"] is None

    r = client.post("/api/users/me/avatar", files={"file": ("me.png", PNG_1PX, "image/png")})
    assert r.status_code == 200, r.text

    after = client.get("/api/auth/me").json()
    assert after["avatar_url"] == r.json()["avatar_url"]


def test_serving_an_unknown_key_404s_in_plain_language(client):
    r = client.get("/media/does-not-exist.png")
    assert r.status_code == 404
